spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://son-test.ccwrivcg14q1.ap-northeast-2.rds.amazonaws.com:5432/postgres'
    username: 'son'
    password: 'thsehdgus1234'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging.level:
    org.hibernate.SQL: debug


jwt:
  header: Authorization
  # jwt secret key
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400